from django.db import models

class Boat(models.Model):
    vuosimalli = models.IntegerField(null=True)
    valmistusvuosi = models.IntegerField(null=True)
    kayttoonottovuosi = models.IntegerField(null=True)
    paavari = models.IntegerField(null=True)
    lisavari = models.IntegerField(null=True)
    maxpituus = models.FloatField(null=True)
    maxnopeus = models.FloatField(null=True)
    maxmoottoriteho = models.FloatField(null=True)
    moottori_teho = models.FloatField(null=True)
    moottori_lkm = models.FloatField(null=True)
    paino = models.FloatField(null=True)
    jokivene = models.NullBooleanField()
    tenonvene = models.NullBooleanField()
    vene_malli = models.CharField(null=True, max_length=99)
    vene_merkki = models.CharField(null=True, max_length=99)
    tyyppi = models.CharField(null=True, max_length=99)
    runkotyyppi = models.CharField(null=True, max_length=99)
    kansirakenne = models.CharField(null=True, max_length=99)
    rungonrakmat = models.CharField(null=True, max_length=99)
    maxhlolkm = models.IntegerField(null=True)
    runkopituus = models.FloatField(null=True)
    maxleveys = models.FloatField(null=True)
    syvays = models.FloatField(null=True)
    kayttokunta_koodi = models.IntegerField(null=True)
    jarnro = models.IntegerField()
    cluster_idx = models.IntegerField(null=True)

